Repository ovh/the-bastion, pull requests merged in 2020-12, with the labels that each got.

#76 fix: sudogen: handle '.' and OS-specific templates correctly
  bin/admin/check-consistency.pl
  bin/admin/install
  bin/helper/osh-accountCreate
  bin/helper/osh-accountDelete
  bin/helper/osh-groupCreate
  bin/helper/osh-groupDelete
  bin/sudogen/generate-sudoers.sh
  tests/functional/docker/docker_build_and_run_tests.sh
  tests/functional/tests.d/370-mfa.sh
Labels: tests:full

#84 Centos
  .github/workflows/tests.yml
  README.md
  bin/admin/packages-check.sh
  bin/helper/osh-groupCreate
  doc/sphinx/installation/basic.rst
  docker/Dockerfile.centos7
  docker/Dockerfile.centos8
  tests/functional/docker/docker_build_and_run_tests.sh
Labels: tests:full

#82 bump to v3.01.02
  doc/CHANGELOG.md
  doc/sphinx/installation/upgrading.rst
  lib/perl/OVH/Bastion.pm
Labels: tests:full

#85 fix: guests: get rid of ghost guest accesses in corner cases
  lib/perl/OVH/Bastion/Plugin/groupSetRole.pm
  tests/functional/tests.d/350-groups.sh
Labels: tests:short

#88 fix: sudogen: don't check for account/groups validity when deleting
  bin/helper/osh-accountDelete
  bin/sudogen/generate-sudoers.sh
Labels: tests:full

#91 release v3.01.03
  doc/CHANGELOG.md
  doc/sphinx/installation/upgrading.rst
  lib/perl/OVH/Bastion.pm
Labels: tests:full

#92 chore: perlcritic: including forgotten .inc files
  bin/dev/perl-critic.sh
  bin/dev/perlcriticrc
  bin/plugin/restricted/accountCreate
  lib/perl/OVH/Bastion/allowdeny.inc
  lib/perl/OVH/Bastion/allowkeeper.inc
  lib/perl/OVH/Bastion/configuration.inc
  lib/perl/OVH/Bastion/execute.inc
  lib/perl/OVH/Bastion/interactive.inc
  lib/perl/OVH/Bastion/log.inc
  lib/perl/OVH/Bastion/mock.inc
  lib/perl/OVH/Bastion/os.inc
  lib/perl/OVH/Bastion/ssh.inc
Labels: tests:full

#79 Fixed wrong default values in bastion.conf comments
  doc/sphinx/installation/upgrading.rst
  etc/bastion/bastion.conf.dist
  lib/perl/OVH/Bastion/configuration.inc
Labels: enhancement

#100 fix bastion.conf.dist after #98
  etc/bastion/bastion.conf.dist
  lib/perl/OVH/Bastion/configuration.inc
  tests/functional/tests.d/330-selfkeys.sh
  tests/functional/tests.d/350-groups.sh
Labels: tests:full

#102 feat: accountModify: add --osh-only (closes #97)
  bin/helper/osh-accountCreate
  bin/helper/osh-accountModify
  bin/plugin/restricted/accountCreate
  bin/plugin/restricted/accountModify
  bin/shell/osh.pl
  doc/sphinx/plugins/restricted/accountCreate.rst
  doc/sphinx/plugins/restricted/accountModify.rst
  lib/perl/OVH/Bastion.pm
  tests/functional/tests.d/340-selfaccesses.sh
Labels: tests:short

#107 fix: groupList: remove 9K group limit
  lib/perl/OVH/Bastion/allowkeeper.inc
Labels: tests:short
