Repository ovh/the-bastion, pull requests merged in 2021-09, with the labels that each got.

#232 enh: better error message when unknown option is used
  bin/shell/osh.pl
Labels: tests:long

#235 enh: accountInfo: add --list-groups
  bin/plugin/restricted/accountInfo
  doc/sphinx/plugins/restricted/accountInfo.rst
  tests/functional/tests.d/325-accountinfo.sh
Labels: tests:short

#238 chore: remove useless 'section' test info
  tests/functional/docker/docker_build_and_run_tests.sh
  tests/functional/launch_tests_on_instance.sh
  tests/functional/tests.d/300-activeness.sh
  tests/functional/tests.d/305-admin-superowner.sh
  tests/functional/tests.d/310-realm.sh
  tests/functional/tests.d/320-base.sh
  tests/functional/tests.d/325-accountinfo.sh
  tests/functional/tests.d/330-selfkeys.sh
  tests/functional/tests.d/340-selfaccesses.sh
  tests/functional/tests.d/350-groups.sh
  tests/functional/tests.d/360-plugins.sh
  tests/functional/tests.d/370-mfa.sh
  tests/functional/tests.d/390-mfa-realm.sh
  tests/functional/tests.d/400-piv.sh
  tests/functional/tests.d/500-http-proxy.sh
  tests/functional/tests.d/900-strict-checking.sh
Labels: tests:full

#239 release v3.05.00
  doc/CHANGELOG.md
  lib/perl/OVH/Bastion.pm
Labels: tests:full

#247 fix: add superowner group requirement
  doc/sphinx/administration/configuration/bastion_conf.rst
  etc/bastion/bastion.conf.dist
Labels: tests:short

#248 fix: groupdel: false positive in lock contention detection
  lib/perl/OVH/Bastion/os.inc
Labels: tests:full
